name: hifi_player
description: Hi-Fi local music player
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.46
  audio_session: ^0.1.25
  permission_handler: ^11.3.1
  on_audio_query: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/hifiplayer.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/hifiplayer.png"
  adaptive_icon_background: "#0B0E12"
  adaptive_icon_foreground: "assets/icon/hifiplayer.png"